name: OSINT Scout Runner

on:
  schedule:
    # This is a cron schedule. This runs every hour, on the hour.
    - cron: '0 * * * *'
  workflow_dispatch: # This adds a button to run it manually from the Actions tab on GitHub

jobs:
  run-scouts:
    runs-on: ubuntu-latest # The scout runs on a fresh, powerful Linux VM every time
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests

      - name: Run RSS Scout
        # This will run your rss_scout.py script from within the repo.
        # We need to create this script next.
        run: python ./scouts/rss_scout.py
        env:
          BUNKER_API_KEY: ${{ secrets.BUNKER_API_KEY }}